In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
import pandas as pd
import numpy as np

In [5]:
import pickle
split_list = [0,1,2,3,4]

dataset = 'adult_race_gender'
save_dir = '../save_fairness/{:s}/'.format(dataset)
seed = 42
shidden ='_512_512_'
str_loss = 'CE'

item = 0


    
for split in split_list:
    savepath = save_dir+'MMPFNN_arq'+shidden+'lossCE_seed'+str(seed)+'_split'+str(split)+'_minimax.pkl'
    with open(savepath, 'rb') as f:
        save_data = pickle.load(f)
    if item == 0:
        results_table = save_data['group_test_stats'].copy()
    else:
        results_table = pd.concat([results_table,save_data['group_test_stats'].copy()])
    item += 1    

    
for split in split_list:
    savepath = save_dir+'MMPFNN_arq'+shidden+'lossCE_seed'+str(seed)+'_split'+str(split)+'_balanced.pkl'
    with open(savepath, 'rb') as f:
        save_data = pickle.load(f)
    if item == 0:
        results_table = save_data['group_test_stats'].copy()
    else:
        results_table = pd.concat([results_table,save_data['group_test_stats'].copy()])
    item += 1
    
for split in split_list:
    savepath = save_dir+'MMPFNN_arq'+shidden+'lossCE_seed'+str(seed)+'_split'+str(split)+'_naive.pkl'
    with open(savepath, 'rb') as f:
        save_data = pickle.load(f)
    if item == 0:
        results_table = save_data['group_test_stats'].copy()
    else:
        results_table = pd.concat([results_table,save_data['group_test_stats'].copy()])
    item += 1
    
for split in split_list:
    savepath = save_dir+'apstar_llr_{:d}.pkl'.format(split)
    with open(savepath, 'rb') as f:
        save_data = pickle.load(f)
    if item == 0:
        results_table = save_data['group_test_stats'].copy()
    else:
        results_table = pd.concat([results_table,save_data['group_test_stats'].copy()])
    item += 1

In [6]:
# print(results_table)

In [7]:
results_table.groupby(['model','group']).mean()

                       ACC        BS        CE   Entropy       ECE       MCE  \
model      group
apstar_llr 0      0.946123  0.083445  0.151725  0.227438  0.035227  0.118308
           1      0.846558  0.206019  0.321555  0.341359  0.029479  0.083561
           2      0.913578  0.124853  0.216869  0.279910  0.034100  0.082095
           3      0.805475  0.263942  0.404149  0.400630  0.009876  0.028856
balanced   0      0.946603  0.080108  0.152741  0.181742  0.024625  0.212859
           1      0.844817  0.217021  0.390595  0.317214  0.036177  0.116865
           2      0.907376  0.137594  0.296438  0.216517  0.014905  0.094651
           3      0.797931  0.276495  0.483731  0.370872  0.030037  0.054353
minimax    0      0.943357  0.084080  0.140289  0.155289  0.016375  0.168654
           1      0.843478  0.210017  0.330037  0.313692  0.032937  0.098544
           2      0.915112  0.126410  0.229178  0.213106  0.013134  0.089572
           3      0.811520  0.261227  0.414252  0.387857  0.019770  0.045531

                  ACC_prior
model      group
apstar_llr 0       0.930384
           1       0.776085
           2       0.874393
           3       0.672690
balanced   0       0.930384
           1       0.776085
           2       0.874393
           3       0.672690
minimax    0       0.930384
           1       0.776085
           2       0.874393
           3       0.672690